(function(){
  const DATA = [
    { fr: 'Le chien', pt: 'O cachorro' },
    { fr: 'Le chat', pt: 'O gato' },
    { fr: 'Le cheval', pt: 'O cavalo' },
    { fr: 'La vache', pt: 'A vaca' },
    { fr: 'Le cochon', pt: 'O porco' },
    { fr: 'Le mouton', pt: 'O carneiro' },
    { fr: 'La chèvre', pt: 'A cabra' },
    { fr: 'Le lapin', pt: 'O coelho' },
    { fr: 'Le lion', pt: 'O leão' },
    { fr: 'Le tigre', pt: 'O tigre' },
    { fr: "L'éléphant", pt: 'O elefante' },
    { fr: 'La girafe', pt: 'A girafa' },
    { fr: 'Le singe', pt: 'O macaco' },
    { fr: "L'ours", pt: 'O urso' },
    { fr: 'Le loup', pt: 'O lobo' },
    { fr: 'Le renard', pt: 'A raposa' },
    { fr: 'Le cerf', pt: 'O cervo / veado' },
    { fr: "L'oiseau", pt: 'O pássaro' },
    { fr: "L'aigle", pt: 'A águia' },
    { fr: 'Le canard', pt: 'O pato' },
    { fr: 'Le poulet / Le coq', pt: 'O frango / O galo' },
    { fr: 'La poule', pt: 'A galinha' },
    { fr: 'Le poisson', pt: 'O peixe' },
    { fr: 'Le requin', pt: 'O tubarão' },
    { fr: 'La baleine', pt: 'A baleia' },
    { fr: 'Le dauphin', pt: 'O golfinho' },
    { fr: 'La tortue', pt: 'A tartaruga' },
    { fr: 'Le serpent', pt: 'A cobra' },
    { fr: 'La grenouille', pt: 'A rã' },
    { fr: "L'abeille", pt: 'A abelha' },
    { fr: 'Le papillon', pt: 'A borboleta' },
    { fr: 'La fourmi', pt: 'A formiga' },
    { fr: "L'araignée", pt: 'A aranha' },
    { fr: 'La souris', pt: 'O rato' },
    { fr: 'Le rat', pt: 'A ratazana' },
  ];

  QuizCore.createGame(DATA, { title: 'Animais — Francês → Português', rounds: 10 });
})();
