(function(){
  const DATA = [
    { it: 'Il cane', pt: 'O cachorro' },
    { it: 'Il gatto', pt: 'O gato' },
    { it: 'Il cavallo', pt: 'O cavalo' },
    { it: 'La mucca', pt: 'A vaca' },
    { it: 'Il maiale', pt: 'O porco' },
    { it: 'La pecora', pt: 'A ovelha' },
    { it: 'La capra', pt: 'A cabra' },
    { it: 'Il coniglio', pt: 'O coelho' },
    { it: 'Il leone', pt: 'O leão' },
    { it: 'La tigre', pt: 'O tigre' },
    { it: "L'elefante", pt: 'O elefante' },
    { it: 'La giraffa', pt: 'A girafa' },
    { it: 'La scimmia', pt: 'O macaco' },
    { it: "L'orso", pt: 'O urso' },
    { it: 'Il lupo', pt: 'O lobo' },
    { it: 'La volpe', pt: 'A raposa' },
    { it: 'Il cervo', pt: 'O cervo / veado' },
    { it: "L'uccello", pt: 'O pássaro' },
    { it: "L'aquila", pt: 'A águia' },
    { it: 'L\'anatra', pt: 'O pato' },
    { it: 'Il pollo / Il gallo', pt: 'O frango / O galo' },
    { it: 'La gallina', pt: 'A galinha' },
    { it: 'Il pesce', pt: 'O peixe' },
    { it: 'Lo squalo', pt: 'O tubarão' },
    { it: 'La balena', pt: 'A baleia' },
    { it: 'Il delfino', pt: 'O golfinho' },
    { it: 'La tartaruga', pt: 'A tartaruga' },
    { it: 'Il serpente', pt: 'A cobra' },
    { it: 'La rana', pt: 'A rã' },
    { it: "L'ape", pt: 'A abelha' },
    { it: 'La farfalla', pt: 'A borboleta' },
    { it: 'La formica', pt: 'A formiga' },
    { it: "Il ragno", pt: 'A aranha' },
    { it: 'Il topo', pt: 'O rato' },
    { it: 'Il ratto', pt: 'A ratazana' },
  ];

  QuizCore.createGame(DATA, { title: 'Animali — Italiano → Português', rounds: 10 });
})();
