window.FR_NIVEIS = {
  N1: [
    { fr: 'aller', pt: 'ir' },
    { fr: 'avoir', pt: 'ter' },
    { fr: 'être', pt: 'ser' },
    { fr: 'faire', pt: 'fazer' },
    { fr: 'parler', pt: 'falar' },
    { fr: 'écouter', pt: 'escutar' },
    { fr: 'acheter', pt: 'comprar' },
    { fr: 'aider', pt: 'ajudar' },
    { fr: 'aimer', pt: 'amar' },
    { fr: 'arrêter', pt: 'parar' },
    { fr: 'arriver', pt: 'chegar' },
    { fr: 'attendre', pt: 'esperar' },
    { fr: 'boire', pt: 'beber' },
    { fr: 'changer', pt: 'mudar' },
    { fr: 'chercher', pt: 'procurar' },
    { fr: 'choisir', pt: 'escolher' },
    { fr: 'commander', pt: 'ordenar' },
    { fr: 'comprendre', pt: 'compreender' },
    { fr: 'conduire', pt: 'dirigir' },
    { fr: 'connaître', pt: 'conhecer' }
  ],
  N2: [
    { fr: 'fleur', pt: 'flor' },
    { fr: 'fruit', pt: 'fruta' },
    { fr: 'fromage', pt: 'queijo' },
    { fr: 'gare', pt: 'estação' },
    { fr: 'garçon', pt: 'rapaz' },
    { fr: 'grand', pt: 'grande' },
    { fr: 'idée', pt: 'ideia' },
    { fr: 'immeuble', pt: 'prédio' },
    { fr: 'Italie', pt: 'Itália' },
    { fr: 'journal', pt: 'jornal' },
    { fr: 'jupe', pt: 'saia' },
    { fr: 'jus', pt: 'suco' },
    { fr: 'lait', pt: 'leite' },
    { fr: 'légume', pt: 'legume' },
    { fr: 'magasin', pt: 'loja' },
    { fr: 'maison', pt: 'casa' },
    { fr: 'match', pt: 'partida' },
    { fr: 'médecin', pt: 'médico' },
    { fr: 'médicament', pt: 'remédio' },
    { fr: 'menu', pt: 'cardápio' }
  ],
  N3: [
    { fr: 'âge', pt: 'idade' },
    { fr: 'an', pt: 'ano' },
    { fr: 'après', pt: 'depois' },
    { fr: 'aujourd\'hui', pt: 'hoje' },
    { fr: 'avant', pt: 'antes' },
    { fr: 'bon', pt: 'bom' },
    { fr: 'calendrier', pt: 'calendário' },
    { fr: 'campagne', pt: 'campo' },
    { fr: 'carte', pt: 'mapa' },
    { fr: 'ce', pt: 'este' },
    { fr: 'cela', pt: 'isso' },
    { fr: 'chez', pt: 'em casa' },
    { fr: 'chien', pt: 'cachorro' },
    { fr: 'chose', pt: 'coisa' },
    { fr: 'cinéma', pt: 'cinema' },
    { fr: 'classe', pt: 'classe' },
    { fr: 'client', pt: 'cliente' },
    { fr: 'club', pt: 'clube' },
    { fr: 'comment', pt: 'como' },
    { fr: 'compagnie', pt: 'companhia' }
  ],
  N4: [
    { fr: 'eau', pt: 'água' },
    { fr: 'école', pt: 'escola' },
    { fr: 'élève', pt: 'aluno' },
    { fr: 'email', pt: 'email' },
    { fr: 'enfant', pt: 'criança' },
    { fr: 'entreprise', pt: 'empresa' },
    { fr: 'épicerie', pt: 'mercearia' },
    { fr: 'escalier', pt: 'escada' },
    { fr: 'Espagne', pt: 'Espanha' },
    { fr: 'espoir', pt: 'esperança' },
    { fr: 'et', pt: 'e' },
    { fr: 'étage', pt: 'andar' },
    { fr: 'été', pt: 'verão' },
    { fr: 'étranger', pt: 'estrangeiro' },
    { fr: 'étudiant', pt: 'estudante' },
    { fr: 'euro', pt: 'euro' },
    { fr: 'facile', pt: 'fácil' },
    { fr: 'famille', pt: 'família' },
    { fr: 'femme', pt: 'mulher' },
    { fr: 'fille', pt: 'filha' }
  ],
  N5: [
    { fr: 'jambe', pt: 'perna' },
    { fr: 'janvier', pt: 'janeiro' },
    { fr: 'japonais', pt: 'japonês' },
    { fr: 'jardin', pt: 'jardim' },
    { fr: 'jaune', pt: 'amarelo' },
    { fr: 'je', pt: 'eu' },
    { fr: 'jeu', pt: 'jogo' },
    { fr: 'jeudi', pt: 'quinta' },
    { fr: 'jeune', pt: 'jovem' },
    { fr: 'joie', pt: 'alegria' },
    { fr: 'joli', pt: 'bonito' },
    { fr: 'jouet', pt: 'brinquedo' },
    { fr: 'jour', pt: 'dia' },
    { fr: 'journal', pt: 'diário' },
    { fr: 'journée', pt: 'jornada' },
    { fr: 'juillet', pt: 'julho' },
    { fr: 'juin', pt: 'junho' },
    { fr: 'kiosque', pt: 'quiosque' },
    { fr: 'large', pt: 'largo' },
    { fr: 'lent', pt: 'lento' }
  ],
  N6: [
    { fr: 'neige', pt: 'neve' },
    { fr: 'neuf', pt: 'novo' },
    { fr: 'noir', pt: 'preto' },
    { fr: 'nom', pt: 'nome' },
    { fr: 'nombre', pt: 'número' },
    { fr: 'nous', pt: 'nós' },
    { fr: 'nouveau', pt: 'novo' },
    { fr: 'nuit', pt: 'noite' },
    { fr: 'numéro', pt: 'número' },
    { fr: 'occupé', pt: 'ocupado' },
    { fr: 'octobre', pt: 'outubro' },
    { fr: 'oeil', pt: 'olho' },
    { fr: 'oiseau', pt: 'pássaro' },
    { fr: 'on', pt: 'nós' },
    { fr: 'orange', pt: 'laranja' },
    { fr: 'ordinateur', pt: 'computador' },
    { fr: 'où', pt: 'onde' },
    { fr: 'ou', pt: 'ou' },
    { fr: 'oui', pt: 'sim' },
    { fr: 'pain', pt: 'pão' }
  ],
  N7: [
    { fr: 'radio', pt: 'rádio' },
    { fr: 'rapide', pt: 'rápido' },
    { fr: 'rapidement', pt: 'rapidamente' },
    { fr: 'réfrigérateur', pt: 'geladeira' },
    { fr: 'rendez-vous', pt: 'encontro' },
    { fr: 'repas', pt: 'refeição' },
    { fr: 'réservation', pt: 'reserva' },
    { fr: 'retard', pt: 'atraso' },
    { fr: 'réveil', pt: 'despertador' },
    { fr: 'revue', pt: 'revista' },
    { fr: 'rhume', pt: 'resfriado' },
    { fr: 'riche', pt: 'rico' },
    { fr: 'rien', pt: 'nada' },
    { fr: 'riz', pt: 'arroz' },
    { fr: 'robe', pt: 'vestido' },
    { fr: 'rose', pt: 'rosa' },
    { fr: 'rouge', pt: 'vermelho' },
    { fr: 'rugby', pt: 'rúgbi' },
    { fr: 'sa', pt: 'sua' },
    { fr: 'sac', pt: 'bolsa' }
  ],
  N8: [
    { fr: 'vacances', pt: 'férias' },
    { fr: 'vache', pt: 'vaca' },
    { fr: 'vainqueur', pt: 'vencedor' },
    { fr: 'vaisselle', pt: 'louça' },
    { fr: 'végétal', pt: 'vegetal' },
    { fr: 'vélo', pt: 'bicicleta' },
    { fr: 'vendeur', pt: 'vendedor' },
    { fr: 'vendredi', pt: 'sexta' },
    { fr: 'vent', pt: 'vento' },
    { fr: 'vente', pt: 'venda' },
    { fr: 'ventre', pt: 'barriga' },
    { fr: 'vert', pt: 'verde' },
    { fr: 'veste', pt: 'jaqueta' },
    { fr: 'vêtement', pt: 'roupa' },
    { fr: 'viande', pt: 'carne' },
    { fr: 'vie', pt: 'vida' },
    { fr: 'vieux', pt: 'velho' },
    { fr: 'ville', pt: 'cidade' },
    { fr: 'vin', pt: 'vinho' },
    { fr: 'visite', pt: 'visita' }
  ],
  N9: [
    { fr: 'agréable', pt: 'agradável' },
    { fr: 'aide', pt: 'ajuda' },
    { fr: 'album', pt: 'álbum' },
    { fr: 'aliment', pt: 'alimento' },
    { fr: 'allemand', pt: 'alemão' },
    { fr: 'alors', pt: 'então' },
    { fr: 'ami', pt: 'amigo' },
    { fr: 'amour', pt: 'amor' },
    { fr: 'ancien', pt: 'antigo' },
    { fr: 'anglais', pt: 'inglês' },
    { fr: 'animal', pt: 'animal' },
    { fr: 'année', pt: 'ano' },
    { fr: 'anniversaire', pt: 'aniversário' },
    { fr: 'août', pt: 'agosto' },
    { fr: 'apéritif', pt: 'aperitivo' },
    { fr: 'appartement', pt: 'apartamento' },
    { fr: 'arbre', pt: 'árvore' },
    { fr: 'argent', pt: 'dinheiro' },
    { fr: 'armée', pt: 'exército' },
    { fr: 'armoire', pt: 'guarda-roupa' }
  ],
  N10: [
    { fr: 'cabine', pt: 'cabine' },
    { fr: 'cadeau', pt: 'presente' },
    { fr: 'café', pt: 'café' },
    { fr: 'cahier', pt: 'caderno' },
    { fr: 'calculatrice', pt: 'calculadora' },
    { fr: 'calendrier', pt: 'calendário' },
    { fr: 'campagne', pt: 'campanha' },
    { fr: 'canapé', pt: 'sofá' },
    { fr: 'caravane', pt: 'caravana' },
    { fr: 'carrefour', pt: 'cruzamento' },
    { fr: 'carte', pt: 'cartão' },
    { fr: 'ceinture', pt: 'cinto' },
    { fr: 'centre', pt: 'centro' },
    { fr: 'céréales', pt: 'cereais' },
    { fr: 'ces', pt: 'estes' },
    { fr: 'cette', pt: 'esta' },
    { fr: 'chaise', pt: 'cadeira' },
    { fr: 'chambre', pt: 'quarto' },
    { fr: 'champagne', pt: 'champanha' },
    { fr: 'championnat', pt: 'campeonato' }
  ],
  N11: [
    { fr: 'énergie', pt: 'energia' },
    { fr: 'engagement', pt: 'compromisso' },
    { fr: 'ensemble', pt: 'junto' },
    { fr: 'entretien', pt: 'entrevista' },
    { fr: 'enveloppe', pt: 'envelope' },
    { fr: 'environ', pt: 'aproximadamente' },
    { fr: 'époque', pt: 'época' },
    { fr: 'essai', pt: 'teste' },
    { fr: 'essence', pt: 'essência' },
    { fr: 'essentiel', pt: 'essencial' },
    { fr: 'état', pt: 'estado' },
    { fr: 'étendre', pt: 'estender' },
    { fr: 'éternel', pt: 'eterno' },
    { fr: 'éternité', pt: 'eternidade' },
    { fr: 'éthique', pt: 'ética' },
    { fr: 'étiquette', pt: 'etiqueta' },
    { fr: 'étoile', pt: 'estrela' },
    { fr: 'étonnant', pt: 'surpreendente' },
    { fr: 'étonner', pt: 'espantar' },
    { fr: 'étroit', pt: 'estreito' }
  ],
  N12: [
    { fr: 'évidemment', pt: 'evidentemente' },
    { fr: 'évidence', pt: 'evidência' },
    { fr: 'évident', pt: 'evidente' },
    { fr: 'évier', pt: 'pia' },
    { fr: 'évincer', pt: 'eliminar' },
    { fr: 'évitable', pt: 'evitável' },
    { fr: 'évité', pt: 'evitado' },
    { fr: 'éviter', pt: 'evitar' },
    { fr: 'évocation', pt: 'evocação' },
    { fr: 'évolué', pt: 'evoluído' },
    { fr: 'évoluer', pt: 'evoluir' },
    { fr: 'évolution', pt: 'evolução' },
    { fr: 'évoquer', pt: 'evocar' },
    { fr: 'exacerbation', pt: 'exacerbação' },
    { fr: 'exacerber', pt: 'exacerbar' },
    { fr: 'exact', pt: 'exato' },
    { fr: 'exactitude', pt: 'exatidão' },
    { fr: 'exagération', pt: 'exageração' },
    { fr: 'exagéré', pt: 'exagerado' },
    { fr: 'exagérer', pt: 'exagerar' }
  ]
};
