window.FR_NIVEIS = {
  L1: [
    { fr: 'bonjour', pt: 'bom dia' },
    { fr: 'bonsoir', pt: 'boa noite' },
    { fr: 'salut', pt: 'oi' },
    { fr: 'au revoir', pt: 'até logo' },
    { fr: 'merci', pt: 'obrigado' },
    { fr: "s'il vous plaît", pt: 'por favor' },
    { fr: 'oui', pt: 'sim' },
    { fr: 'non', pt: 'não' },
    { fr: 'comment', pt: 'como' },
    { fr: 'où', pt: 'onde' },
    { fr: 'pourquoi', pt: 'porquê' },
    { fr: 'quand', pt: 'quando' },
    { fr: 'et', pt: 'e' },
    { fr: 'avec', pt: 'com' },
    { fr: 'dans', pt: 'em, dentro' },
    { fr: "de, d'", pt: 'de' },
    { fr: 'à', pt: 'a' },
    { fr: 'ami(e)', pt: 'amigo(a)' },
    { fr: 'père', pt: 'pai' },
    { fr: 'mère', pt: 'mãe' },
    { fr: 'fils', pt: 'filho' },
    { fr: 'fille', pt: 'menina, garota / filha' },
    { fr: 'frère', pt: 'irmão' },
    { fr: 'sœur', pt: 'irmã' },
    { fr: 'famille', pt: 'família' },
    { fr: 'maison', pt: 'casa' },
    { fr: 'école', pt: 'escola' },
    { fr: 'hôtel', pt: 'hotel' },
    { fr: 'restaurant', pt: 'restaurante' },
    { fr: 'café', pt: 'café' },
    { fr: 'pain', pt: 'pão' },
    { fr: 'eau', pt: 'água' },
    { fr: 'vin', pt: 'vinho' },
    { fr: 'fromage', pt: 'queijo' },
    { fr: 'fruit', pt: 'fruta' },
    { fr: 'viande', pt: 'carne' },
    { fr: 'poisson', pt: 'peixe' },
    { fr: 'pomme', pt: 'maçã' },
    { fr: 'chocolat', pt: 'chocolate' },
    { fr: 'sel', pt: 'sal' },
    { fr: 'sucre', pt: 'açúcar' },
    { fr: 'œuf', pt: 'ovo' },
    { fr: 'beurre', pt: 'manteiga' },
    { fr: 'grand(e)', pt: 'grande' },
    { fr: 'petit(e)', pt: 'pequeno(a)' },
    { fr: 'beau, belle', pt: 'bonito(a), lindo(a)' },
    { fr: 'bon(ne)', pt: 'bom(a)' }
  ],
  L2: [
    { fr: 'être', pt: 'ser / estar' },
    { fr: 'avoir', pt: 'ter' },
    { fr: 'aller', pt: 'ir' },
    { fr: 'faire', pt: 'fazer' },
    { fr: 'parler', pt: 'falar' },
    { fr: 'manger', pt: 'comer' },
    { fr: 'boire', pt: 'beber' },
    { fr: 'dormir', pt: 'dormir' },
    { fr: 'lire', pt: 'ler' },
    { fr: 'écrire', pt: 'escrever' },
    { fr: 'voir', pt: 'ver' },
    { fr: 'entendre', pt: 'ouvir' },
    { fr: 'comprendre', pt: 'compreender' },
    { fr: 'savoir', pt: 'saber' },
    { fr: 'pouvoir', pt: 'poder' },
    { fr: 'vouloir', pt: 'querer' },
    { fr: 'devoir', pt: 'dever' },
    { fr: 'aimer', pt: 'gostar / amar' },
    { fr: 'acheter', pt: 'comprar' },
    { fr: 'vendre', pt: 'vender' },
    { fr: 'travailler', pt: 'trabalhar' },
    { fr: 'étudier', pt: 'estudar' },
    { fr: 'habiter', pt: 'morar' },
    { fr: 'voyager', pt: 'viajar' },
    { fr: 'arriver', pt: 'chegar' },
    { fr: 'partir', pt: 'partir' },
    { fr: 'attendre', pt: 'esperar' },
    { fr: 'répondre', pt: 'responder' },
    { fr: 'demander', pt: 'pedir / perguntar' },
    { fr: 'donner', pt: 'dar' },
    { fr: 'prendre', pt: 'pegar / tomar' },
    { fr: 'mettre', pt: 'colocar' },
    { fr: 'trouver', pt: 'achar / encontrar' },
    { fr: 'regarder', pt: 'olhar / assistir' },
    { fr: 'écouter', pt: 'escutar' },
    { fr: 'fermer', pt: 'fechar' },
    { fr: 'ouvrir', pt: 'abrir' },
    { fr: 'venir', pt: 'vir' }
  ],
  L3: [
    { fr: 'jour', pt: 'dia' },
    { fr: 'semaine', pt: 'semana' },
    { fr: 'mois', pt: 'mês' },
    { fr: 'an, année', pt: 'ano' },
    { fr: 'lundi', pt: 'segunda-feira' },
    { fr: 'mardi', pt: 'terça-feira' },
    { fr: 'mercredi', pt: 'quarta-feira' },
    { fr: 'jeudi', pt: 'quinta-feira' },
    { fr: 'vendredi', pt: 'sexta-feira' },
    { fr: 'samedi', pt: 'sábado' },
    { fr: 'dimanche', pt: 'domingo' },
    { fr: 'janvier', pt: 'janeiro' },
    { fr: 'février', pt: 'fevereiro' },
    { fr: 'mars', pt: 'março' },
    { fr: 'avril', pt: 'abril' },
    { fr: 'mai', pt: 'maio' },
    { fr: 'juin', pt: 'junho' },
    { fr: 'juillet', pt: 'julho' },
    { fr: 'août', pt: 'agosto' },
    { fr: 'septembre', pt: 'setembro' },
    { fr: 'octobre', pt: 'outubro' },
    { fr: 'novembre', pt: 'novembro' },
    { fr: 'décembre', pt: 'dezembro' },
    { fr: 'printemps', pt: 'primavera' },
    { fr: 'été', pt: 'verão' },
    { fr: 'automne', pt: 'outono' },
    { fr: 'hiver', pt: 'inverno' },
    { fr: 'chaud(e)', pt: 'quente' },
    { fr: 'froid(e)', pt: 'frio(a)' },
    { fr: 'très', pt: 'muito' },
    { fr: 'beaucoup', pt: 'muito' },
    { fr: 'peu', pt: 'pouco' },
    { fr: 'toujours', pt: 'sempre' },
    { fr: 'jamais', pt: 'nunca' },
    { fr: 'déjà', pt: 'já' },
    { fr: 'encore', pt: 'ainda' },
    { fr: 'maintenant', pt: 'agora' },
    { fr: 'après', pt: 'depois' },
    { fr: 'avant', pt: 'antes' },
    { fr: "aujourd'hui", pt: 'hoje' },
    { fr: 'demain', pt: 'amanhã' },
    { fr: 'hier', pt: 'ontem' }
  ],
  L4: [
    { fr: 'ville', pt: 'cidade' },
    { fr: 'quartier', pt: 'bairro' },
    { fr: 'rue', pt: 'rua' },
    { fr: 'avenue', pt: 'avenida' },
    { fr: 'boulevard', pt: 'bulevar' },
    { fr: 'place', pt: 'praça' },
    { fr: 'parc', pt: 'parque' },
    { fr: 'jardin', pt: 'jardim' },
    { fr: 'église', pt: 'igreja' },
    { fr: 'musée', pt: 'museu' },
    { fr: 'cinéma', pt: 'cinema' },
    { fr: 'théâtre', pt: 'teatro' },
    { fr: 'bibliothèque', pt: 'biblioteca' },
    { fr: 'poste', pt: 'correio' },
    { fr: 'banque', pt: 'banco' },
    { fr: 'magasin', pt: 'loja' },
    { fr: 'boutique', pt: 'boutique / loja' },
    { fr: 'marché', pt: 'mercado' },
    { fr: 'supermarché', pt: 'supermercado' },
    { fr: 'boulangerie', pt: 'padaria' },
    { fr: 'boucherie', pt: 'açougue' },
    { fr: 'fromagerie', pt: 'loja de queijos' },
    { fr: 'pâtisserie', pt: 'confeitaria' },
    { fr: 'épicerie', pt: 'mercearia' },
    { fr: 'pharmacie', pt: 'farmácia' },
    { fr: 'hôpital', pt: 'hospital' },
    { fr: 'mairie', pt: 'prefeitura' },
    { fr: 'gare', pt: 'estação' },
    { fr: 'aéroport', pt: 'aeroporto' },
    { fr: 'métro', pt: 'metrô' },
    { fr: 'bus', pt: 'ônibus' },
    { fr: 'train', pt: 'trem' },
    { fr: 'avion', pt: 'avião' },
    { fr: 'bateau', pt: 'barco' },
    { fr: 'vélo', pt: 'bicicleta' },
    { fr: 'voiture', pt: 'carro' },
    { fr: 'chauffeur', pt: 'motorista' },
    { fr: 'billet', pt: 'bilhete / passagem' },
    { fr: 'carte', pt: 'cartão / mapa' },
    { fr: 'adresse', pt: 'endereço' },
    { fr: 'numéro', pt: 'número' },
    { fr: 'téléphone', pt: 'telefone' }
  ],
  L5: [
    { fr: 'agréable', pt: 'agradável' },
    { fr: 'désagréable', pt: 'desagradável' },
    { fr: 'content(e)', pt: 'contente' },
    { fr: 'fatigué(e)', pt: 'cansado(a)' },
    { fr: 'ennuyeux(euse)', pt: 'chato(a)' },
    { fr: 'drôle', pt: 'engraçado(a)' },
    { fr: 'gentil(le)', pt: 'gentil' },
    { fr: 'difficile', pt: 'difícil' },
    { fr: 'facile', pt: 'fácil' },
    { fr: 'cher(ère)', pt: 'caro(a)' },
    { fr: 'bon marché', pt: 'barato' },
    { fr: 'court(e)', pt: 'curto(a)' },
    { fr: 'long(ue)', pt: 'longo(a)' },
    { fr: 'large', pt: 'largo(a)' },
    { fr: 'étroit(e)', pt: 'estreito(a)' },
    { fr: 'foncé(e)', pt: 'escuro(a)' },
    { fr: 'clair(e)', pt: 'claro(a)' },
    { fr: 'ancien(ne)', pt: 'antigo(a)' },
    { fr: 'nouveau, nouvelle', pt: 'novo(a)' },
    { fr: 'dernier(ère)', pt: 'último(a)' },
    { fr: 'premier(ère)', pt: 'primeiro(a)' },
    { fr: 'même', pt: 'mesmo(a)' },
    { fr: 'autre', pt: 'outro(a)' },
    { fr: 'chaque', pt: 'cada' },
    { fr: 'certain(e)', pt: 'certo(a)' },
    { fr: 'seul(e)', pt: 'sozinho(a)' },
    { fr: 'ensemble', pt: 'juntos' },
    { fr: 'pendant', pt: 'durante' },
    { fr: 'depuis', pt: 'desde' },
    { fr: 'jusqu\'à', pt: 'até' },
    { fr: 'environ', pt: 'cerca de' },
    { fr: 'surtout', pt: 'principalmente' },
    { fr: 'ainsi', pt: 'assim' },
    { fr: 'donc', pt: 'portanto' },
    { fr: 'car', pt: 'pois' },
    { fr: 'parce que', pt: 'porque' },
    { fr: 'puisque', pt: 'já que' },
    { fr: 'bien que', pt: 'embora' }
  ],
  L6: [
    { fr: 'confiance', pt: 'confiança' },
    { fr: 'croyance', pt: 'crença' },
    { fr: 'espérance', pt: 'esperança' },
    { fr: 'compétition', pt: 'competição' },
    { fr: 'championnat', pt: 'campeonato' },
    { fr: 'course', pt: 'corrida' },
    { fr: 'concours', pt: 'concurso' },
    { fr: 'exposition', pt: 'exposição' },
    { fr: 'conférence', pt: 'conferência' },
    { fr: 'entretien', pt: 'entrevista' },
    { fr: 'compagnie', pt: 'companhia' },
    { fr: 'affaires', pt: 'negócios' },
    { fr: 'coordinateur(trice)', pt: 'coordenador(a)' },
    { fr: 'facteur(trice)', pt: 'carteiro(a) / fator' },
    { fr: 'avocat(e)', pt: 'advogado(a)' },
    { fr: 'dentiste', pt: 'dentista' },
    { fr: 'médecin', pt: 'médico(a)' },
    { fr: 'directeur(trice)', pt: 'diretor(a)' },
    { fr: 'gérant(e)', pt: 'gerente' },
    { fr: 'secrétaire', pt: 'secretário(a)' },
    { fr: 'employé(e)', pt: 'funcionário(a)' },
    { fr: 'entreprise', pt: 'empresa' },
    { fr: 'bureau', pt: 'escritório' },
    { fr: 'réunion', pt: 'reunião' },
    { fr: 'contrat', pt: 'contrato' },
    { fr: 'salaire', pt: 'salário' },
    { fr: 'impôt', pt: 'imposto' },
    { fr: 'retraite', pt: 'aposentadoria' },
    { fr: 'assurance', pt: 'seguro' },
    { fr: 'héritage', pt: 'herança' },
    { fr: 'succession', pt: 'sucessão' },
    { fr: 'patrimoine', pt: 'patrimônio' },
    { fr: 'investissement', pt: 'investimento' }
  ]
};
