(function(){
  const DATA = [
    { it: 'Io sarò', pt: 'Eu serei / estarei' },
    { it: 'Tu sarai', pt: 'Tu serás / estarás' },
    { it: 'Lui/Lei sarà', pt: 'Ele/ Ela será / estará' },
    { it: 'Noi saremo', pt: 'Nós seremos / estaremos' },
    { it: 'Voi sarete', pt: 'Vocês serão / estarão' },
    { it: 'Loro saranno', pt: 'Eles/ Elas serão / estarão' },
    { it: 'Io avrò', pt: 'Eu terei' },
    { it: 'Tu avrai', pt: 'Tu terás' },
    { it: 'Lui/Lei avrà', pt: 'Ele/ Ela terá' },
    { it: 'Noi avremo', pt: 'Nós teremos' },
    { it: 'Voi avrete', pt: 'Vocês terão' },
    { it: 'Loro avranno', pt: 'Eles/ Elas terão' },
    { it: 'Io farò', pt: 'Eu farei' },
    { it: 'Tu farai', pt: 'Tu farás' },
    { it: 'Lui/Lei farà', pt: 'Ele/ Ela fará' },
    { it: 'Noi faremo', pt: 'Nós faremos' },
    { it: 'Voi farete', pt: 'Vocês farão' },
    { it: 'Loro faranno', pt: 'Eles/ Elas farão' },
    { it: 'Io andrò', pt: 'Eu irei' },
    { it: 'Tu andrai', pt: 'Tu irás' },
    { it: 'Lui/Lei andrà', pt: 'Ele/ Ela irá' },
    { it: 'Noi andremo', pt: 'Nós iremos' },
    { it: 'Voi andrete', pt: 'Vocês irão' },
    { it: 'Loro andranno', pt: 'Eles/ Elas irão' },
    { it: 'Io dovrò', pt: 'Eu terei que / deverei' },
    { it: 'Tu dovrai', pt: 'Tu terás que / deverás' },
    { it: 'Lui/Lei dovrà', pt: 'Ele/ Ela terá que / deverá' },
    { it: 'Noi dovremo', pt: 'Nós teremos que / deveremos' },
    { it: 'Voi dovrete', pt: 'Vocês terão que / deverão' },
    { it: 'Loro dovranno', pt: 'Eles/ Elas terão que / deverão' },
    { it: 'Io vorrò', pt: 'Eu quererei' },
    { it: 'Tu vorrai', pt: 'Tu quererás' },
    { it: 'Lui/Lei vorrà', pt: 'Ele/ Ela quererá' },
    { it: 'Noi vorremo', pt: 'Nós quereremos' },
    { it: 'Voi vorrete', pt: 'Vocês quererão' },
    { it: 'Loro vorranno', pt: 'Eles/ Elas quererão' },
    { it: 'Io potrò', pt: 'Eu poderei' },
    { it: 'Tu potrai', pt: 'Tu poderás' },
    { it: 'Lui/Lei potrà', pt: 'Ele/ Ela poderá' },
    { it: 'Noi potremo', pt: 'Nós poderemos' },
    { it: 'Voi potrete', pt: 'Vocês poderão' },
    { it: 'Loro potranno', pt: 'Eles/ Elas poderão' },
    { it: 'Io vedrò', pt: 'Eu verei' },
    { it: 'Tu vedrai', pt: 'Tu verás' },
    { it: 'Lui/Lei vedrà', pt: 'Ele/ Ela verá' },
    { it: 'Noi vedremo', pt: 'Nós veremos' },
    { it: 'Voi vedrete', pt: 'Vocês verão' },
    { it: 'Loro vedranno', pt: 'Eles/ Elas verão' },
    { it: 'Io saprò', pt: 'Eu saberei' },
    { it: 'Tu saprai', pt: 'Tu saberás' },
    { it: 'Lui/Lei saprà', pt: 'Ele/ Ela saberá' },
    { it: 'Noi sapremo', pt: 'Nós saberemos' },
    { it: 'Voi saprete', pt: 'Vocês saberão' },
    { it: 'Loro sapranno', pt: 'Eles/ Elas saberão' },
    { it: 'Io verrò', pt: 'Eu virei' },
    { it: 'Tu verrai', pt: 'Tu virás' },
    { it: 'Lui/Lei verrà', pt: 'Ele/ Ela virá' },
    { it: 'Noi verremo', pt: 'Nós viremos' },
    { it: 'Voi verrete', pt: 'Vocês virão' },
    { it: 'Loro verranno', pt: 'Eles/ Elas virão' },
    { it: 'Io morirò', pt: 'Eu morrerei' },
    { it: 'Tu morirai', pt: 'Tu morrerás' },
    { it: 'Lui/Lei morirà', pt: 'Ele/ Ela morrerá' },
    { it: 'Noi moriremo', pt: 'Nós morreremos' },
    { it: 'Voi morirete', pt: 'Vocês morrerão' },
    { it: 'Loro moriranno', pt: 'Eles/ Elas morrerão' },
    { it: 'Io riceverò', pt: 'Eu receberei' },
    { it: 'Tu riceverai', pt: 'Tu receberás' },
    { it: 'Lui/Lei riceverà', pt: 'Ele/ Ela receberá' },
    { it: 'Noi riceveremo', pt: 'Nós receberemos' },
    { it: 'Voi riceverete', pt: 'Vocês receberão' },
    { it: 'Loro riceveranno', pt: 'Eles/ Elas receberão' },
    { it: 'Io pagherò', pt: 'Eu pagarei' },
    { it: 'Tu pagherai', pt: 'Tu pagarás' },
    { it: 'Lui/Lei pagherà', pt: 'Ele/ Ela pagará' },
    { it: 'Noi pagheremo', pt: 'Nós pagaremos' },
    { it: 'Voi pagherete', pt: 'Vocês pagarão' },
    { it: 'Loro pagheranno', pt: 'Eles/ Elas pagarão' },
    { it: 'Io manderò', pt: 'Eu enviarei' },
    { it: 'Tu manderai', pt: 'Tu enviarás' },
    { it: 'Lui/Lei manderà', pt: 'Ele/ Ela enviará' },
    { it: 'Noi manderemo', pt: 'Nós enviaremos' },
    { it: 'Voi manderete', pt: 'Vocês enviarão' },
    { it: 'Loro manderanno', pt: 'Eles/ Elas enviarão' },
    { it: 'Io rientrerò', pt: 'Eu entrarei novamente' },
    { it: 'Tu rientrerai', pt: 'Tu entrarás novamente' },
    { it: 'Lui/Lei rientrerà', pt: 'Ele/ Ela entrará novamente' },
    { it: 'Noi rientreremo', pt: 'Nós entraremos novamente' },
    { it: 'Voi rientrerete', pt: 'Vocês entrarão novamente' },
    { it: 'Loro rientreranno', pt: 'Eles/ Elas entrarão novamente' },
  ];

  QuizCore.createGame(DATA, { title: 'Futuro Semplice — Italiano → Português', rounds: 10 });
})();
