(function(){
  const DATA = [
    { fr: 'Je serai', pt: 'Eu serei / estarei' },
    { fr: 'Tu seras', pt: 'Tu serás / estarás' },
    { fr: 'Il/Elle sera', pt: 'Ele/ Ela será / estará' },
    { fr: 'Nous serons', pt: 'Nós seremos / estaremos' },
    { fr: 'Vous serez', pt: 'Vocês serão / estarão' },
    { fr: 'Ils/Elles seront', pt: 'Eles/ Elas serão / estarão' },
    { fr: "J'aurai", pt: 'Eu terei / terei' },
    { fr: 'Tu auras', pt: 'Tu terás' },
    { fr: 'Il/Elle aura', pt: 'Ele/ Ela terá' },
    { fr: 'Nous aurons', pt: 'Nós teremos' },
    { fr: 'Vous aurez', pt: 'Vocês terão' },
    { fr: 'Ils/Elles auront', pt: 'Eles/ Elas terão' },
    { fr: 'Je ferai', pt: 'Eu farei' },
    { fr: 'Tu feras', pt: 'Tu farás' },
    { fr: 'Il/Elle fera', pt: 'Ele/ Ela fará' },
    { fr: 'Nous ferons', pt: 'Nós faremos' },
    { fr: 'Vous ferez', pt: 'Vocês farão' },
    { fr: 'Ils/Elles feront', pt: 'Eles/ Elas farão' },
    { fr: 'Je viendrai', pt: 'Eu virei / virei' },
    { fr: 'Tu viendras', pt: 'Tu virás' },
    { fr: 'Il/Elle viendra', pt: 'Ele/ Ela virá' },
    { fr: 'Nous viendrons', pt: 'Nós viremos' },
    { fr: 'Vous viendrez', pt: 'Vocês virão' },
    { fr: 'Ils/Elles viendront', pt: 'Eles/ Elas virão' },
    { fr: 'Je saurai', pt: 'Eu saberei' },
    { fr: 'Tu sauras', pt: 'Tu saberás' },
    { fr: 'Il/Elle saura', pt: 'Ele/ Ela saberá' },
    { fr: 'Nous saurons', pt: 'Nós saberemos' },
    { fr: 'Vous saurez', pt: 'Vocês saberão' },
    { fr: 'Ils/Elles sauront', pt: 'Eles/ Elas saberão' },
    { fr: 'Je devrai', pt: 'Eu terei que / deverei' },
    { fr: 'Tu devras', pt: 'Tu terás que / deverás' },
    { fr: 'Il/Elle devra', pt: 'Ele/ Ela terá que / deverá' },
    { fr: 'Nous devrons', pt: 'Nós teremos que / deveremos' },
    { fr: 'Vous devrez', pt: 'Vocês terão que / deverão' },
    { fr: 'Ils/Elles devront', pt: 'Eles/ Elas terão que / deverão' },
    { fr: 'Je voudrai', pt: 'Eu quererei' },
    { fr: 'Tu voudras', pt: 'Tu quererás' },
    { fr: 'Il/Elle voudra', pt: 'Ele/ Ela quererá' },
    { fr: 'Nous voudrons', pt: 'Nós quereremos' },
    { fr: 'Vous voudrez', pt: 'Vocês quererão' },
    { fr: 'Ils/Elles voudront', pt: 'Eles/ Elas quererão' },
    { fr: 'Je pourrai', pt: 'Eu poderei' },
    { fr: 'Tu pourras', pt: 'Tu poderás' },
    { fr: 'Il/Elle pourra', pt: 'Ele/ Ela poderá' },
    { fr: 'Nous pourrons', pt: 'Nós poderemos' },
    { fr: 'Vous pourrez', pt: 'Vocês poderão' },
    { fr: 'Ils/Elles pourront', pt: 'Eles/ Elas poderão' },
    { fr: 'Je verrai', pt: 'Eu verei' },
    { fr: 'Tu verras', pt: 'Tu verás' },
    { fr: 'Il/Elle verra', pt: 'Ele/ Ela verá' },
    { fr: 'Nous verrons', pt: 'Nós veremos' },
    { fr: 'Vous verrez', pt: 'Vocês verão' },
    { fr: 'Ils/Elles verront', pt: 'Eles/ Elas verão' },
    { fr: 'Je tiendrai', pt: 'Eu terei / segurarei' },
    { fr: 'Tu tiendras', pt: 'Tu terás / segurarás' },
    { fr: 'Il/Elle tiendra', pt: 'Ele/ Ela terá / segurará' },
    { fr: 'Nous tiendrons', pt: 'Nós teremos / seguremos' },
    { fr: 'Vous tiendrez', pt: 'Vocês terão / segurarão' },
    { fr: 'Ils/Elles tiendront', pt: 'Eles/ Elas terão / segurarão' },
    { fr: 'J\'irai', pt: 'Eu irei' },
    { fr: 'Tu iras', pt: 'Tu irás' },
    { fr: 'Il/Elle ira', pt: 'Ele/ Ela irá' },
    { fr: 'Nous irons', pt: 'Nós iremos' },
    { fr: 'Vous irez', pt: 'Vocês irão' },
    { fr: 'Ils/Elles iront', pt: 'Eles/ Elas irão' },
    { fr: 'Je mourrai', pt: 'Eu morrerei' },
    { fr: 'Tu mourras', pt: 'Tu morrerás' },
    { fr: 'Il/Elle mourra', pt: 'Ele/ Ela morrerá' },
    { fr: 'Nous mourrons', pt: 'Nós morreremos' },
    { fr: 'Vous mourrez', pt: 'Vocês morrerão' },
    { fr: 'Ils/Elles mourront', pt: 'Eles/ Elas morrerão' },
    { fr: 'Je recevrai', pt: 'Eu receberei' },
    { fr: 'Tu recevras', pt: 'Tu receberás' },
    { fr: 'Il/Elle recevra', pt: 'Ele/ Ela receberá' },
    { fr: 'Nous recevrons', pt: 'Nós receberemos' },
    { fr: 'Vous recevrez', pt: 'Vocês receberão' },
    { fr: 'Ils/Elles recevront', pt: 'Eles/ Elas receberão' },
    { fr: 'Je paierai', pt: 'Eu pagarei' },
    { fr: 'Tu paieras', pt: 'Tu pagarás' },
    { fr: 'Il/Elle paiera', pt: 'Ele/ Ela pagará' },
    { fr: 'Nous paierons', pt: 'Nós pagaremos' },
    { fr: 'Vous paierez', pt: 'Vocês pagarão' },
    { fr: 'Ils/Elles paieront', pt: 'Eles/ Elas pagarão' },
    { fr: 'J\'enverrai', pt: 'Eu enviarei' },
    { fr: 'Tu enverras', pt: 'Tu enviarás' },
    { fr: 'Il/Elle enverra', pt: 'Ele/ Ela enviará' },
    { fr: 'Nous enverrons', pt: 'Nós enviaremos' },
    { fr: 'Vous enverrez', pt: 'Vocês enviarão' },
    { fr: 'Ils/Elles enverront', pt: 'Eles/ Elas enviarão' },
    { fr: 'Je rentrerai', pt: 'Eu entrarei novamente' },
    { fr: 'Tu rentreras', pt: 'Tu entrarás novamente' },
    { fr: 'Il/Elle rentrera', pt: 'Ele/ Ela entrará novamente' },
    { fr: 'Nous rentrerons', pt: 'Nós entraremos novamente' },
    { fr: 'Vous rentrerez', pt: 'Vocês entrarão novamente' },
    { fr: 'Ils/Elles rentreront', pt: 'Eles/ Elas entrarão novamente' },
  ];

  QuizCore.createGame(DATA, { title: 'Future Simple — Francês → Português', rounds: 10 });
})();
