(function(){
  const DATA = [
    { fr: 'La fourchette', pt: 'O garfo' },
    { fr: 'Le couteau', pt: 'A faca' },
    { fr: 'La cuillère', pt: 'A colher' },
    { fr: 'La cuillère à soupe', pt: 'A concha / colher de sopa' },
    { fr: 'La cuillère à café', pt: 'A colher de café' },
    { fr: 'La fourchette à poisson', pt: 'O garfo de peixe' },
    { fr: 'Le couteau à steak', pt: 'A faca de bife' },
    { fr: 'L\'assiette', pt: 'O prato' },
    { fr: 'L\'assiette plate', pt: 'O prato raso' },
    { fr: 'L\'assiette creuse', pt: 'O prato fundo' },
    { fr: 'L\'assiette à dessert', pt: 'O prato de sobremesa' },
    { fr: 'L\'assiette à soupe', pt: 'O prato de sopa' },
    { fr: 'Le bol', pt: 'A tigela / caneca' },
    { fr: 'La tasse', pt: 'A xícara' },
    { fr: 'La tasse à café', pt: 'A xícara de café' },
    { fr: 'La tasse à thé', pt: 'A xícara de chá' },
    { fr: 'Le verre', pt: 'O copo' },
    { fr: 'Le verre à eau', pt: 'O copo de água' },
    { fr: 'Le verre à vin', pt: 'A taça de vinho' },
    { fr: 'Le verre à champagne', pt: 'A taça de champanhe' },
    { fr: 'La soucoupe', pt: 'O pires' },
    { fr: 'Le sous-plat', pt: 'O jogo americano' },
    { fr: 'La serviette', pt: 'O guardanapo' },
    { fr: 'La serviette en papier', pt: 'O guardanapo de papel' },
    { fr: 'La serviette en tissu', pt: 'O guardanapo de pano' },
    { fr: 'Le torchon', pt: 'O pano de prato' },
    { fr: 'La nappe', pt: 'A toalha de mesa' },
    { fr: 'Le set de table', pt: 'O jogo americano / individual' },
    { fr: 'Le plat', pt: 'O travessa / prato' },
    { fr: 'Le plat à four', pt: 'A assadeira' },
    { fr: 'La poêle', pt: 'A frigideira' },
    { fr: 'La casserole', pt: 'A panela' },
    { fr: 'La marmite', pt: 'A panela / caldeirão' },
    { fr: 'La passoire', pt: 'O escorredor' },
    { fr: 'L\'écumoire', pt: 'A escumadeira' },
    { fr: 'Le fouet', pt: 'O batedor / fouet' },
    { fr: 'La spatule', pt: 'A espátula' },
    { fr: 'La louche', pt: 'A concha' },
    { fr: 'Le doseur', pt: 'A medida' },
    { fr: 'Le rouleau à pâtisserie', pt: 'O rolo de massa' },
    { fr: 'Le bol à mélanger', pt: 'A tigela de mistura' },
    { fr: 'Le saladier', pt: 'A saladeira' },
    { fr: 'La carafe', pt: 'A garrafa' },
    { fr: 'La théière', pt: 'O bule de chá' },
    { fr: 'La cafetière', pt: 'A cafeteira' },
    { fr: 'Le sucrier', pt: 'O açucareiro' },
    { fr: 'Le pot à beurre', pt: 'O manteigueira' },
    { fr: 'Le sel et le poivre', pt: 'O sal e a pimenta' },
    { fr: 'La salière', pt: 'O saleiro' },
    { fr: 'Le poivrier', pt: 'O pimenteiro' },
  ];

  QuizCore.createGame(DATA, { title: 'Louças — Francês → Português', rounds: 10 });
})();
