(function(){
  const DATA = [
    { fr: 'La tête', pt: 'A cabeça' },
    { fr: 'Le crâne', pt: 'O crânio' },
    { fr: 'Le cerveau', pt: 'O cérebro' },
    { fr: 'Le visage', pt: 'O rosto' },
    { fr: "L'œil (pl. les yeux)", pt: 'O olho (os olhos)' },
    { fr: 'Le sourcil', pt: 'A sobrancelha' },
    { fr: 'La paupière', pt: 'A pálpebra' },
    { fr: 'Le nez', pt: 'O nariz' },
    { fr: 'La joue', pt: 'A bochecha' },
    { fr: 'La bouche', pt: 'A boca' },
    { fr: 'Les lèvres', pt: 'Os lábios' },
    { fr: 'La dent', pt: 'O dente' },
    { fr: 'La langue', pt: 'A língua' },
    { fr: 'Le menton', pt: 'O queixo' },
    { fr: 'Le cou', pt: 'O pescoço' },
    { fr: 'La gorge', pt: 'A garganta' },
    { fr: "L'épaule", pt: 'O ombro' },
    { fr: 'Les épaules', pt: 'Os ombros' },
    { fr: 'Les cheveux', pt: 'O cabelo' },
    { fr: 'Le front', pt: 'A testa' },
    { fr: 'Les oreilles', pt: 'As orelhas' },
    { fr: 'Le bras', pt: 'O braço' },
    { fr: 'Le coude', pt: 'O cotovelo' },
    { fr: 'Le poignet', pt: 'O pulso' },
    { fr: 'La main', pt: 'A mão' },
    { fr: 'Le doigt', pt: 'O dedo' },
    { fr: "L'ongle", pt: 'A unha' },
    { fr: 'La poitrine', pt: 'O peito / O tórax' },
    { fr: 'Le cœur', pt: 'O coração' },
    { fr: 'Le poumon', pt: 'O pulmão' },
    { fr: "L'estomac", pt: 'O estômago' },
    { fr: 'Le ventre', pt: 'A barriga / O ventre' },
    { fr: 'Le foie', pt: 'O fígado' },
    { fr: "L'intestin", pt: 'O intestino' },
    { fr: 'Le rein', pt: 'O rim' },
    { fr: 'Le dos', pt: 'As costas' },
    { fr: 'La colonne vertébrale', pt: 'A coluna vertebral' },
    { fr: 'La hanche', pt: 'O quadril' },
    { fr: 'La jambe', pt: 'A perna' },
    { fr: 'La cuisse', pt: 'A coxa' },
    { fr: 'Le genou', pt: 'O joelho' },
    { fr: 'La cheville', pt: 'O tornozelo' },
    { fr: 'Le pied', pt: 'O pé' },
    { fr: "L'orteil / Le doigt de pied", pt: 'O dedo do pé' },
    { fr: 'Le sang', pt: 'O sangue' },
    { fr: "L'os", pt: 'O osso' },
    { fr: 'Le muscle', pt: 'O músculo' },
    { fr: 'La peau', pt: 'A pele' },
  ];

  QuizCore.createGame(DATA, { title: 'Partes do Corpo — Francês → Português', rounds: 10 });
})();
