(function(){
  const DATA = [
    { fr: 'La maison', pt: 'A casa' },
    { fr: 'La cuisine', pt: 'A cozinha' },
    { fr: 'Le salon', pt: 'A sala de estar' },
    { fr: 'La chambre', pt: 'O quarto' },
    { fr: 'La salle de bain', pt: 'O banheiro' },
    { fr: 'Les toilettes', pt: 'O banheiro / WC' },
    { fr: 'Le jardin', pt: 'O jardim' },
    { fr: 'Le garage', pt: 'A garagem' },
    { fr: 'Le sous-sol', pt: 'O porão' },
    { fr: 'Le grenier', pt: 'O sótão' },
    { fr: 'L\'entrée', pt: 'A entrada / hall' },
    { fr: 'Le couloir', pt: 'O corredor' },
    { fr: 'L\'escalier', pt: 'A escada' },
    { fr: 'Le balcon', pt: 'A varanda' },
    { fr: 'La terrasse', pt: 'O terraço' },
    { fr: 'Le toit', pt: 'O telhado' },
    { fr: 'Le mur', pt: 'A parede' },
    { fr: 'La porte', pt: 'A porta' },
    { fr: 'La fenêtre', pt: 'A janela' },
    { fr: 'Le plancher', pt: 'O chão' },
    { fr: 'Le plafond', pt: 'O teto' },
    { fr: 'La salle à manger', pt: 'A sala de jantar' },
    { fr: 'Le bureau', pt: 'O escritório' },
    { fr: 'La bibliothèque', pt: 'A biblioteca / estante' },
    { fr: 'La cave', pt: 'A adega / porão' },
    { fr: 'Le veranda', pt: 'A varanda' },
    { fr: 'La terrasse', pt: 'O terraço' },
    { fr: 'Le porche', pt: 'A varanda coberta' },
    { fr: 'Le patio', pt: 'O pátio' },
    { fr: 'La clôture', pt: 'A cerca' },
    { fr: 'Le portail', pt: 'O portão' },
    { fr: 'La cheminée', pt: 'A chaminé' },
    { fr: 'Le grenier', pt: 'O sótão' },
    { fr: 'La buanderie', pt: 'A lavanderia' },
    { fr: 'Le dressing', pt: 'O closet / guarda-roupa' },
    { fr: 'La cave', pt: 'A adega' },
    { fr: 'L\'atelier', pt: 'A oficina' },
    { fr: 'Le cellier', pt: 'O despensa' },
  ];

  QuizCore.createGame(DATA, { title: 'Partes da Casa — Francês → Português', rounds: 10 });
})();
